{
 "title": "CI etcd",
 "time": { "from": "now-8d", "to": "now" },
 "panels": [
  {
   "title": "db size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(etcd_debugging_mvcc_db_total_size_in_bytes) by (cluster_job)"
    }
   ]
  },
  {
   "title": "fsync p99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[2m])) by (le, cluster_job))"
    }
   ]
  },
  {
   "title": "fsync p999",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[2m])) by (le, cluster_job))"
    }
   ]
  }
 ]
}